### ISSUE TITLE
Adicionar opção "Trabalhe conosco" no Portal da Rede BVs 

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/suporte-bvs#2]
Criar opção no menu superior e na área de rodapé do Portal para validação em ambiente de testes.

**Comment by marcioalvessilva** [comment]
Conforme contato com a @pierrima me coloco a disposição.

Segue link
https://reddes.bvsalud.org/vaga-gerente-de-tecnologia-2021/

Inserir apenas no portal em português - inserir o link trabalhe conosco no menu principal e no rodapé.

Grato!

**Comment by viniciusandrade** [comment]
@pierrima em acordo com @veronicaabdala vamos realizar a divulgação da vaga neste momento somente no Portal da Rede BVS, neste caso estou alterando o título deste issue e seguimos a disposição.

**Comment by viniciusandrade** [comment]
Vaga adicionada nos destaques do Portal da Rede BVS. 

Obrigado @pierrima e @marcioalvessilva.
