### ISSUE TITLE
Carregamento Lis e Direve

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/suporte-bvs#3]
boa tarde!
@marcoslmori por favor verificar porque não esta carregando conteúdo no LIS e DIREVE do portal BVS MS

**Comment by viniciusandrade** [comment]
@marcoslmori complementando olhei este tema rapidamente com o Marcio e acredito que seja necessário coordenar com eles a atualização dos plugins pois em nossas instâncias os conteúdos estão sendo carregados normalmente.
Obrigado.

**Comment by marcioalvessilva** [comment]
Existe outro chamado atualizado!
